name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,x86_64-apple-darwin,aarch64-apple-darwin,aarch64-unknown-linux-gnu

      - name: Install macOS cross-compilation tools
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Build for Linux (x86_64)
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for Linux (ARM64)
        run: |
          TARGET_CC=aarch64-linux-gnu-gcc cargo build --release --target aarch64-unknown-linux-gnu
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

      - name: Install macOS cross-compilation tools
        uses: actions-rs/install@v0.1
        with:
          crate: cross
          use-tool-cache: true

      - name: Build for macOS (x86_64)
        run: cross build --release --target x86_64-apple-darwin

      - name: Build for macOS (ARM64)
        run: cross build --release --target aarch64-apple-darwin

      - name: Rename binaries
        run: |
          cp target/x86_64-unknown-linux-gnu/release/gs gs-linux-amd64
          cp target/aarch64-unknown-linux-gnu/release/gs gs-linux-arm64
          cp target/x86_64-apple-darwin/release/gs gs-darwin-amd64
          cp target/aarch64-apple-darwin/release/gs gs-darwin-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gs-darwin-amd64
            gs-darwin-arm64
            gs-linux-amd64
            gs-linux-arm64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
