name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  # Combined build job for all platforms
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: linux-arm64
            deps: g++-aarch64-linux-gnu libc6-dev-arm64-cross
            env: CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          - os: macos-latest
            target: x86_64-apple-darwin
            name: darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: darwin-arm64
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Install dependencies
        if: matrix.deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.deps }}
          
      - name: Run tests
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo test --verbose
          
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        env: ${{ matrix.env }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gs-${{ matrix.name }}
          path: target/${{ matrix.target }}/release/gs

  # Create release with all binaries
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Prepare release files
        run: |
          mkdir -p release-files
          cp artifacts/gs-linux-amd64/gs release-files/gs-linux-amd64
          cp artifacts/gs-linux-arm64/gs release-files/gs-linux-arm64
          cp artifacts/gs-darwin-amd64/gs release-files/gs-darwin-amd64
          cp artifacts/gs-darwin-arm64/gs release-files/gs-darwin-arm64
          chmod +x release-files/*
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-files/*
          generate_release_notes: true
